"""Build the display fonts: Montserrat (Latin) + DejaVu Sans (math, Greek, super/subscripts)
+ LVGL's symbol icons, at 12, 16 and 24 px. Also writes include/glyphs.h, the sorted list of
every character the fonts can draw, so the firmware knows what it may show.

Needs Node (npx downloads LVGL's lv_font_conv) and the font files from the LVGL library
(.pio/libdeps/<env>/lvgl/scripts/built_in_font). Run from the project root:
    python tools/make_fonts.py
"""

import glob
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = sorted(glob.glob(os.path.join(ROOT, '.pio', 'libdeps', '*', 'lvgl', 'scripts', 'built_in_font')))
if not SRC:
    sys.exit('LVGL font sources not found: build once so PlatformIO fetches LVGL.')
SRC = SRC[0]

# Montserrat: printable ASCII and Latin-1 (accents, ½ ± × ÷ ² ³ · °).
LATIN = [
    (0x20, 0x7E),
    (0xA0, 0xFF),
    (0x2013, 0x2014),
    (0x2018, 0x2019),
    (0x201C, 0x201D),
    (0x2022, 0x2022),
    (0x2026, 0x2026),
    (0x20AC, 0x20AC),
]
# DejaVu Sans: what answers about maths and science need.
MATH = [
    (0x0391, 0x03A1),
    (0x03A3, 0x03A9),
    (0x03B1, 0x03C9),
    (0x03D1, 0x03D1),
    (0x03D5, 0x03D5),
    (0x03F5, 0x03F5),  # Greek
    (0x02B0, 0x02B0),
    (0x02B2, 0x02B3),
    (0x02B7, 0x02B8),
    (0x02E1, 0x02E3),  # ʰ ʲ ʳ ʷ ʸ ˡ ˢ ˣ
    (0x1D40, 0x1D40),
    (0x1D43, 0x1D43),
    (0x1D47, 0x1D49),
    (0x1D4D, 0x1D4D),
    (0x1D4F, 0x1D50),
    (0x1D52, 0x1D52),
    (0x1D56, 0x1D58),
    (0x1D5B, 0x1D5B),
    (0x1D62, 0x1D65),
    (0x1D9C, 0x1D9C),
    (0x1DA0, 0x1DA0),
    (0x1DBB, 0x1DBB),
    (0x2C7C, 0x2C7C),  # superscript/subscript letters
    (0x2070, 0x2071),
    (0x2074, 0x208E),
    (0x2090, 0x209C),  # superscripts and subscripts
    (0x2032, 0x2033),
    (0x2044, 0x2044),  # ′ ″ ⁄
    (0x2102, 0x2102),
    (0x210F, 0x210F),
    (0x2113, 0x2113),
    (0x2115, 0x2115),
    (0x211A, 0x211A),
    (0x211D, 0x211D),
    (0x2124, 0x2124),  # ℂ ℏ ℓ ℕ ℚ ℝ ℤ
    (0x2150, 0x215E),  # ⅓ ⅔ ⅛ ...
    (0x2190, 0x2194),
    (0x21D0, 0x21D4),  # arrows
    (0x2200, 0x2200),
    (0x2202, 0x2203),
    (0x2205, 0x2205),
    (0x2207, 0x2209),
    (0x220F, 0x220F),
    (0x2211, 0x2213),
    (0x2218, 0x221B),
    (0x221D, 0x221E),
    (0x2220, 0x2220),
    (0x2225, 0x222C),
    (0x222E, 0x222E),
    (0x2234, 0x2235),
    (0x223C, 0x223C),
    (0x2245, 0x2245),
    (0x2248, 0x2248),
    (0x2260, 0x2261),
    (0x2264, 0x2265),
    (0x226A, 0x226B),
    (0x2282, 0x2283),
    (0x2286, 0x2287),
    (0x2295, 0x2295),
    (0x2297, 0x2297),
    (0x22A5, 0x22A5),
    (0x22C5, 0x22C5),
    (0x22EF, 0x22EF),
    (0x2308, 0x230B),  # operators, relations, sets, ⌈⌉⌊⌋
    (0x2713, 0x2713),
    (0x2717, 0x2717),  # ✓ ✗
]
# LVGL's built-in icons (LV_SYMBOL_*), from its own font generator.
SYMBOLS = [
    int(c)
    for c in (
        '61441,61448,61451,61452,61453,61457,61459,61461,61465,61468,61473,61478,61479,61480,61502,'
        '61507,61512,61515,61516,61517,61521,61522,61523,61524,61543,61544,61550,61552,61553,61556,'
        '61559,61560,61561,61563,61587,61589,61636,61637,61639,61641,61664,61671,61674,61683,61724,'
        '61732,61787,61931,62016,62017,62018,62019,62020,62087,62099,62212,62189,62810,63426,63650'
    ).split(',')
]


def ranges(rs):
    return ','.join(f'0x{a:X}' if a == b else f'0x{a:X}-0x{b:X}' for a, b in rs)


npx = 'npx.cmd' if os.name == 'nt' else 'npx'
for size in (12, 16, 24):
    out = os.path.join(ROOT, 'src', 'fonts', f'perch_font_{size}.c')
    os.makedirs(os.path.dirname(out), exist_ok=True)
    cmd = [
        npx,
        '--yes',
        'lv_font_conv',
        '--no-compress',
        '--no-prefilter',
        '--bpp',
        '4',
        '--size',
        str(size),
        '--format',
        'lvgl',
        '--force-fast-kern-format',
        '--lv-include',
        'lvgl.h',
        '--lv-font-name',
        f'perch_font_{size}',
        '-o',
        out,
        '--font',
        os.path.join(SRC, 'Montserrat-Medium.ttf'),
        '-r',
        ranges(LATIN),
        '--font',
        os.path.join(SRC, 'DejaVuSans.ttf'),
        '-r',
        ranges(MATH),
        '--font',
        os.path.join(SRC, 'FontAwesome5-Solid+Brands+Regular.woff'),
        '-r',
        ','.join(map(str, SYMBOLS)),
    ]
    subprocess.run(cmd, check=True)
    print('wrote', os.path.relpath(out, ROOT))

codes = sorted({c for a, b in LATIN + MATH for c in range(a, b + 1)} | set(SYMBOLS))
with open(os.path.join(ROOT, 'include', 'glyphs.h'), 'w', encoding='utf-8', newline='\n') as f:
    f.write('// Generated by tools/make_fonts.py: every character the display fonts can draw.\n')
    f.write('#pragma once\n#include <stdint.h>\n\n')
    f.write(f'static const uint16_t DISPLAY_GLYPHS[{len(codes)}] = {{\n')
    for i in range(0, len(codes), 12):
        f.write('  ' + ', '.join(f'0x{c:04X}' for c in codes[i : i + 12]) + ',\n')
    f.write('};\n\n')
    f.write('inline bool displayHasGlyph(uint32_t code) {\n')
    f.write('  if (code >= 0x20 && code < 0x7F) return true;\n')
    f.write('  int lo = 0, hi = sizeof DISPLAY_GLYPHS / sizeof DISPLAY_GLYPHS[0] - 1;\n')
    f.write('  while (lo <= hi) {\n    const int mid = (lo + hi) / 2;\n')
    f.write('    if (DISPLAY_GLYPHS[mid] == code) return true;\n')
    f.write('    if (DISPLAY_GLYPHS[mid] < code) lo = mid + 1; else hi = mid - 1;\n  }\n  return false;\n}\n')
print(len(codes), 'glyphs')
